[build-system]
requires = ["setuptools>=61.0"] 
build-backend = "setuptools.build_meta"

[project]
name = "Yamada"
version = "0.0.2"
authors = [
  { name="Chad Peterson", email="cp44@illinois.edu" },
]
description = "Calculate the Yamada polynomial of spatial topologies."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
"networkx~=2.8.5", 
"matplotlib==3.5.3", 
"numpy<=1.22.4",
"pytest",
"sphinx",
"cypari~=2.4.1"
]

[project.urls]
"Homepage" = "https://github.com/SPI2Py/Yamada"
"Bug Tracker" = "https://github.com/SPI2Py/Yamada/issues"