name: Python package

on: [push, pull_request, workflow_dispatch]

jobs:


  # Test on all supported Python versions.
  Python:

    strategy:
        matrix:
            python: ['3.9','3.10','3.11']

    runs-on: ubuntu-20.04

    steps:
      - name: Check out code.
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}.
        uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python }}

      - name: Install package.
        run:  pip install .[test]

        # Some unit tests are written in Jupyter notebooks. However, PyTest does not parse notebooks.
        # Therefore, we convert the notebooks to scripts and run the tests on the scripts.
      - name: Ensure all tests reflect the latest Jupyter notebooks.
        run: cd tests && python convert_notebooks_to_scripts.py

      - name: Run tests.
        run:  cd .. && pytest